rauc: register systemd service only if configured
When the PACKAGECONFIG did not include service, bitbake was failing with

  ERROR: rauc-1.10-r0 do_package: Didn't find service unit 'rauc.service', specified in SYSTEMD_SERVICE:rauc-service.

Fixed this by setting the SYSTEMD_SERVICE variable only when the
corresponding service flag in the PACKAGCONFIG variable is also set.

Signed-off-by: Stephan Wurm <stephan.wurm@a-eberle.de>
(cherry picked from commit d8e2c00e3d167f6361e4b8702ec10ac61ce151d8)